import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import StarsCanvas from "@/components/StarBackground";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Srisanth | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <StarsCanvas />
        {children}
      </body>
    </html>
  );
}